name: PaperMobCounter
version: 3.1.0
main: com.kleinercode.plugins.papermobcounter.PaperMobCounter
api-version: 1.21
commands:
  countmobs:
    description: Counts mobs for players
    usage: Usage is /countmobs <start | stop | reset> <EntityType>