name: PaperMobCounter
version: 3.0.0
main: com.floogoobooq.blackomega.papermobcounter.PaperMobCounter
api-version: 1.19
commands:
  countmobs:
    description: Counts mobs for players
    usage: Usage is /countmobs <start | stop | reset> <EntityType>